# Generated by Django 6.0.5 on 2026-06-01 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lokomotywa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text="Seria/oznaczenie, np. 'Pt47', 'EU07'", max_length=100)),
                ('opis', models.TextField(blank=True, help_text='Krótka charakterystyka pojazdu')),
                ('zdjecie', models.ImageField(blank=True, help_text='Ilustracja z boku', null=True, upload_to='lokomotywy/')),
                ('zrodlo_zdjecia', models.CharField(blank=True, help_text="Autor / licencja zdjęcia (np. 'Wikimedia Commons, CC BY-SA 4.0')", max_length=300)),
            ],
            options={
                'verbose_name': 'Lokomotywa',
                'verbose_name_plural': 'Lokomotywy',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Zdarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(help_text="Nazwa zdarzenia, np. 'Katastrofa pod Otłoczynem'", max_length=200)),
                ('data', models.DateField(help_text='Data wypadku')),
                ('miejscowosc', models.CharField(help_text='Miejsce zdarzenia', max_length=150)),
                ('szerokosc', models.FloatField(help_text='Szerokość geograficzna (np. 52.9341) — pinezka na mapie')),
                ('dlugosc', models.FloatField(help_text='Długość geograficzna (np. 18.7150) — pinezka na mapie')),
                ('linia_kolejowa', models.CharField(blank=True, help_text="Numer/nazwa linii kolejowej, np. 'Linia 18'", max_length=100)),
                ('opis', models.TextField(help_text='Przebieg zdarzenia')),
                ('przyczyna', models.TextField(blank=True, help_text='Ustalona przyczyna (jeśli znana)')),
                ('liczba_ofiar', models.PositiveIntegerField(blank=True, help_text='Liczba ofiar śmiertelnych (jeśli znana). Zostaw puste, jeśli brak danych.', null=True)),
                ('lokomotywa', models.ForeignKey(blank=True, help_text='Tabor zaangażowany w zdarzenie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zdarzenia', to='wypadki.lokomotywa')),
            ],
            options={
                'verbose_name': 'Zdarzenie',
                'verbose_name_plural': 'Zdarzenia',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('film', 'Film (YouTube)'), ('podcast', 'Podcast'), ('reportaz', 'Reportaż'), ('artykul', 'Artykuł prasowy'), ('zdjecie', 'Zdjęcie / grafika')], default='artykul', help_text='Rodzaj materiału', max_length=20)),
                ('tytul', models.CharField(help_text='Nazwa materiału', max_length=300)),
                ('url', models.URLField(help_text="Pełny link do materiału lub ID filmu YouTube (np. 'dQw4w9WgXcQ')", max_length=500)),
                ('zrodlo', models.CharField(blank=True, help_text="Pochodzenie materiału (np. 'Polskie Radio', 'Archiwum TVP')", max_length=200)),
                ('zdarzenie', models.ForeignKey(help_text='Zdarzenie, do którego należy materiał', on_delete=django.db.models.deletion.CASCADE, related_name='materialy', to='wypadki.zdarzenie')),
            ],
            options={
                'verbose_name': 'Materiał',
                'verbose_name_plural': 'Materiały',
                'ordering': ['typ', 'tytul'],
            },
        ),
    ]
